In [82]:
 # configuración para notebook con instalación LOCAL
FUENTES_DIR  = '../../Datos-Fuentes/Fuentes/'     # carpeta donde se encuentran archivos .py auxiliares
DATOS_DIR    = '../../Datos-Fuentes/Datos/'      # carpeta donde se encuentran los datasets
MODELOS_DIR  = '../Modelos/'    # carpeta donde se encuentran los modelos
ARCHIVOs_DIR = '../Archivos/'   # carpeta recuperar o copiar archivos

# agrega ruta de busqueda donde tenemos archivos .py
import sys
sys.path.append(FUENTES_DIR)

In [83]:
import pandas as pd      # para trabajar con archivos de datos csv, excel, etc: https://pandas.pydata.org/docs/getting_started/tutorials.html
import chardet           # para detectar la codificación de texto en archivos

nombre_archivo = DATOS_DIR + 'FrutasTrain.csv' # archivo de hojas

#-- detectando la codificación de caracteres usada ----
with open(nombre_archivo, 'rb') as f:
    result = chardet.detect(f.read())  # or readline if the file is large

# recupera el archivo en un objeto dataframe de pandas utilizando la codificación detectada
df = pd.read_csv(nombre_archivo, encoding=result['encoding'])

display(df)

Diametro  Color    Clase
0         10    200  Naranja
1         20     30    Melon
2          8    150  Naranja
3         26     30    Melon
4          7    170  Naranja
5         24     32    Melon
6         20    170  Naranja
7         21    160    Melon
8         21    180  Naranja
9         23    160    Melon
10        22    190  Naranja
11        23    190    Melon
12        24    250  Naranja
13        15     31    Melon
14        15    250  Naranja
15        19     31    Melon

In [84]:
from sklearn import preprocessing
import numpy as np

# %% separa atributos para entrenar de clases
X = np.array(df.iloc[:,:-1])  # recupera todas las columnas salvo la ultima (es la clase)
T = np.array(df.iloc[:,-1])   # recupera solo la ultima columna (es la clase)

clases = np.unique(T)  # obtiene las clases sin repeticiones
print('Las clases del dataset son :', clases)

# Normalizacion con media y desviacion
scaler = preprocessing.StandardScaler()
X = scaler.fit_transform(X)

# Melon = 1, Naranja = -1
T = 2*(T == "Melon")-1

X



Las clases del dataset son : ['Melon' 'Naranja']


array([[-1.50462909,  0.78461053],
       [ 0.23986841, -1.40200899],
       [-1.85352859,  0.14148715],
       [ 1.2865669 , -1.40200899],
       [-2.02797834,  0.3987365 ],
       [ 0.9376674 , -1.37628405],
       [ 0.23986841,  0.3987365 ],
       [ 0.41431816,  0.27011182],
       [ 0.41431816,  0.52736118],
       [ 0.76321765,  0.27011182],
       [ 0.58876791,  0.65598586],
       [ 0.76321765,  0.65598586],
       [ 0.9376674 ,  1.42773392],
       [-0.63238034, -1.38914652],
       [-0.63238034,  1.42773392],
       [ 0.06541866, -1.38914652]])

In [85]:
from ClassNeuronaGral import NeuronaGradiente

###############################################################################
# neurona no lineal sigmoid
ERROR = 1e-03
ALFA = 0.2
FUN = 'tanh'
MAX_ITE = 250

print('\nNeurona con %s' %FUN)

# Entrena perceptrón
modelo = NeuronaGradiente(alpha=ALFA, n_iter=MAX_ITE, FUN=FUN, cotaE=ERROR)
modelo.fit(X, T)
(W, b, iteraciones) = (modelo.w_, modelo.b_, len(modelo.errors_))

Y = modelo.predict(X)

efectividad = 100.0*np.sum(Y==T)/len(Y)

print("%6.2f%% de efectividad con %d iteraciones" % (efectividad, iteraciones ))


Neurona con tanh
100.00% de efectividad con 250 iteraciones


## Calcular

In [86]:
w_diametro = 2.65
w_color = -2.5
b = 0.03

Z = X[:,0]*w_diametro + X[:,1]*w_color + b
Z = np.tanh(Z)

#Z = np.where( Z > 0, 1, -1)
Z = np.where( Z >= 0.8, 1, np.where(Z <= -0.8, -1, 'Indefinido'))
print((Z == 'Indefinido').sum())

np.unique(Z, return_counts=True)



6


(array(['-1', '1', 'Indefinido'], dtype='<U11'), array([4, 6, 6], dtype=int64))

## preg 21

In [87]:
w_diametro = 2.65
w_color = -2.5
b = 0.03

d = 14
c = 140

X_test = np.array([[d, c]])
print(X_test)

X_test = scaler.transform(X_test)
print(X_test)

Z_test = X_test[:,0]*w_diametro + X_test[:,1]*w_color + b
Z_test = np.tanh(Z_test)
print(Z_test)

Z_test = np.where( Z_test >= 0.8, 1, np.where(Z_test <= -0.8, -1, 'Indefinido'))

Z_test




[[ 14 140]]
[[-0.80683009  0.01286247]]
[-0.97270646]


array(['-1'], dtype='<U11')

## preg 22

In [88]:
w_diametro = 2.65
w_color = -2.5
b = 0.03

d = 16
c = 79

X_test = np.array([[d, c]])

X_test = scaler.transform(X_test)

Z_test = X_test[:,0]*w_diametro + X_test[:,1]*w_color + b
Z_test = np.tanh(Z_test)
print(Z_test)

Z_test = np.where( Z_test >= 0.8, 1, np.where(Z_test <= -0.8, -1, 'Indefinido'))

Z_test


[0.63266905]


array(['Indefinido'], dtype='<U11')